### ISSUE TITLE
Not redirected away from Viewer Page 

### ISSUE THREAD

**Issue by rohnnie** [gcivil-nyu-org/fall24-monday-team1#175]
Description: When I login as a gamer and click view events and then try to create an event, I do get the message that Im not allowed, but I DO NOT GET REDIRECTED FROM VIEWER PAGE as mentioned in the testing doc.

Details requested by TA are as below:

Account Used:
Username: rohan.test1
Password: rohan1234

Error: Not redirected when from viewer page when my profile is a gamer.

Steps Followed:
(a) Navigate to View Events tab
(b) Clicked on Create New Event tab
(c) Gets a message that im not allowed but not redirected away from page.

Page URL: http://checkpoint.eba-4drvums3.us-east-1.elasticbeanstalk.com/events/

Expected: I should be redirected away from view events page. 
<img width="1470" alt="Screenshot 2024-11-19 at 2 13 28 PM" src="https://github.com/user-attachments/assets/6b1012ea-67bd-4e6b-bd48-70eb5f720df9">
<img width="1470" alt="Screenshot 2024-11-19 at 2 18 49 PM" src="https://github.com/user-attachments/assets/9ae4ebde-9844-406d-acc4-78f3ed4a9e1a">

**Comment by ad6641** [comment]
This was a typo in the document! Thanks for pointing it out, we will fix it. The app is behaving as actually expected - if you aren't en event organizer or creator, you cannot even enter the create event page, and a message will tell you so.
Closing this issue since this isn't a bug, but we will fix the document so others aren't misled!
