### ISSUE TITLE
Login again after pressing back button or going back manually using trackpad in the browser

### ISSUE THREAD

**Issue by KarthikVV24-11-1999** [gcivil-nyu-org/fall24-monday-team1#190]
Account Used: Karthik
Error: [Forbidden] CSRF verification failed. Request aborted
Steps Followed: 
1. Login to the account
2. Press back button or use trackpad to go back in the browser
3. Observe that the login credentials are maintained in the state
4. Click on the Login button again
5. Log out and try this again 

Expected Results: No error should be thrown, instead the state for the login credentials should be cleared already    

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3JiQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--543a013cee72e3167392481a258ccd6fc601b6f2/Screen%20Recording%202024-11-21%20at%2011.40.38%E2%80%AFPM.mov)

**Comment by ad6641** [comment]
this seems to happen only if the user chooses to save his password. And furthermore, this only happens on some browsers, depending on how they implement saved password autofill. For example, on Arc or Safari on Mac, browser asks user to authenticate themselves before filling these fields, whereas firefox doesn't seem to do that by default just fills the password.

the csrf error is shown because the token is rotated after a successful login. by hitting the back button, browser will use the page in cache, which includes the now inactive csrf. 

fixed this issue by forcing a reload when this page gets loaded from cache

**Comment by KarthikVV24-11-1999** [comment]
Hi, this seems to happen irrespective of whether the password is saved or autofilled, hope you have fixed this as well by forcing the reload. Following is the video on Safari:

https://github.com/user-attachments/assets/f2d113b3-52cd-4f84-bad3-d6ad201aad70

**Comment by ad6641** [comment]
yup the page force reloads now so even this scenario is fixed
